version: "3.7"

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-stage
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_stage
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      - users-db

  exercises:
    build:
      context: ./services/exercises
      dockerfile: Dockerfile
    volumes:
      - "./services/exercises:/usr/src/app"
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - USERS_SERVICE_URL=http://users:5000
      - SECRET_KEY=my_precious
      - DATABASE_URL=postgres://postgres:postgres@exercises-db:5432/exercises_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@exercises-db:5432/exercises_test
    depends_on:
      - users
      - exercises-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  exercises-db:
    build:
      context: ./services/exercises/project/db
      dockerfile: Dockerfile
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-stage
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
        - REACT_APP_API_GATEWAY_URL=${REACT_APP_API_GATEWAY_URL}
        - REACT_APP_EXERCISES_SERVICE_URL=${REACT_APP_EXERCISES_SERVICE_URL}
    expose:
      - 80
    depends_on:
      - users

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-stage
    expose:
      - 8080
    environment:
      - URL=swagger.json
    depends_on:
      - users

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-stage
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client
