"""empty message

Revision ID: 406197f8db39
Revises: 16339764d51d
Create Date: 2020-11-14 15:15:34.741527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406197f8db39'
down_revision = '16339764d51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
